# This file defines the contenttypes on the website. See the documentation for
# details: http://docs.bolt.cm/content#defining-contenttypes

# Pages can be used for the more 'static' pages on your site. Things like
# 'about us', 'contact' or a 'disclaimer'. This content-type has a 'templateselect'
# field, which allows you to override the record_template setting for an
# individual page.
# The taxonomy for this contenttype is defined as 'chapters', which is a so-called
# "grouping" taxonomy. This way you can easily group sets of pages that logically
# belong together. If your site has a 'services' section, in which you'd like to
# list the different types of services a company provides, you can group these
# together.

pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        image:
            type: image
        teaser:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
        template:
            type: templateselect
            filter: '*.twig'
    taxonomy: [ chapters ]
    recordsperpage: 100

items:
    name: Items
    singular_name: Item
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        url:
            type: textarea
            pattern: url
        description:
            type: html
        featured:
            type: select
            values: [ No, Yes ]
            default: null
        country:
            type: select
            values: [ AT, BE, BG, HR, CY, CZ, DK, EE, EU, FI, FR, DE, Global, GR, HU, IE, IT, LV, LT, LU, MT, NL, PL, PT, RO, SK, SI, ES, SE, UK ]
        weight:
            type: select
            values: [1, 2, 3]
        feed_id:
            type: integer
    relations:
        domains:
            multiple: true
            label: Domain
            order: weight
    taxonomy: [ tags, stakeholder ]


domains:
    name: Domains
    singular_name: Domain
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        weight:
            type: integer
            postfix: 'The smaller the number, the higher in the list'
    relations:
        items:
            multiple: true
            label: Items
    sort: weight ASC
    class: \AptiContent\Domain

feeds:
    name: Feeds
    singular_name: Feed
    fields:
        name:
            type: text
            class: large
        url:
            type: textarea
            pattern: url
        errors:
            type: textarea


# possible field types:
# text - varchar(256) - input type text.
# integer - integer - Input field for integer numbers.
# float - double - Input field for floating numbers, stored as 'Double'.
# geolocation - text (65kb) - Input field for geolocation. Enter an address, and the location is geocoded to latitude/longitude coordinates
# imagelist - text (65kb) - Input type for imagelists. Add multiple images with a description. Useful for image sliders, galleries, etcetera.
# image - varchar(256) - image select/upload widget, stored as filename.
# file - varchar(256) - file select/upload widget, stored as filename.
# filelist - text (65kb) - Input type for a list of files. Including a description.
# video - varchar(256) - Video embed widget, stored as filename.
# html - text (65kb) - wysiwyg element.
# textarea - varchar(32768) - Simple, plain < textarea > field.
# markdown - varchar(32768) - Simple, plain < textarea > field, which is parsed as Markdown text.
# datetime - datetime - date and time selector widget.
# date - datetime - date selector widget.
# select - varchar(256) - select with predefined values
# templateselect - varchar(256) - select with template filenames
# checkbox - integer - checkbox-field which is 1 (checked) or 0 (unchecked)


# number (deprecated) - input type decimal(18,9), useful for storing number that need to be sortable
