# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
  - label: Home
    title: This is the first menu item.
    path: homepage
    class: first
  - label: Overview
    path: /page/overview
  - label: Privacy
    path: /page/privacy
  - label: IPR
    path: /page/ipr
    submenu:
      - label: IPR 1
        path: /page/ipr/1
      - label: IPR 2
        path: /page/ipr/2
  - label: IG
    path: /page/ig
    submenu:
      - label: IG 1
        path: /page/ig/1
      - label: IG 2
        path: /page/ig/2
  - label: Startups
    path: /page/startups
  - label: Suggest
    path: /page/suggest

footer:
  - label: Sitemap
    path: /page/sitemap
  - label: Disclaimer
    path: /page/disclaimer
  - label: About Us
    path: /page/about-us