# This file defines the different types of taxonomies in Bolt. See the 
# documentation for details: http://docs.bolt.cm/taxonomies#taxonomies

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    #listing_template: tag-listing.twig #custom template

publisher:
    name: Publisher
    slug: publisher
    singular_name: publisher
    singular_slug: publisher
    behaves_like: categories
    options: [ Government, Civil Society, Industry, European Bodies]

categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options: [ news, events, movies, music, books, life, love, fun ]

stakeholder:
    name: Stakeholder
    slug: stakeholder
    singular_name: Stakeholde
    singular_slug: stakeholder
    behaves_like: categories
    multiple: false
    options: [Government, Civil Society, Industry, Academia, European Bodies]