(function() {

if(window.location.href.indexOf('observatory.mappingtheinternet.eu/bolt/overview/items') > 0) {
  patch_index();
}

function evaluate(text) {
  var found = [];
  get_words().forEach(function(word) {
    found = [].concat(found, text.match(RegExp('\\b'+word+'\\b', 'g')) || []);
  });
  return {
    words: found,
    totalWords: (text.match(/\S+/g) || []).length
  };
}

function patch_index() {
  var trs = $('.dashboardlisting tr');
  var header = trs[0];
  var rows = trs.slice(1);
  $(header).append($('<th>').text('score'));

  rows.map(function() {
    var tr = $(this);
    var url = $('a', tr).attr('href');
    $.get(url, function(html) {
      var desc = $('textarea[name=description]', html).html();
      var stats = evaluate(desc);
      console.log(+url.match(/\d+$/)[0], stats);
      tr.append($('<td>').text('' + stats.words.length + ' / ' + stats.totalWords));
    });
  })
}

function get_words() {
  return [
    "abbey house media v. apple inc.",
    "abuse of powers",
    "academia",
    "access",
    "access to communications",
    "access to data",
    "access to information",
    "access to internet",
    "access to personal data",
    "access to public information",
    "accountability",
    "account information",
    "action plan",
    "activists",
    "adaptation right",
    "ad-blocking",
    "ads",
    "adsl",
    "advertisement",
    "advertising",
    "advisory council",
    "advisory expert groups",
    "advisory group",
    "advocacy",
    "advocate general ",
    "advocate general opinion",
    "aede tax",
    "aerial law enforcement surveillance",
    "affordable access",
    "agency",
    "ag opinion",
    "agreement",
    "alice v. cls bank",
    "alliances",
    "amicus brief",
    "amicus curiae",
    "amendments",
    "analysis",
    "ancillary copyright",
    "android",
    "andrus ansip",
    "annual report",
    "anonimity network",
    "anonymity",
    "anonymity tool",
    "anonymous",
    "ansip",
    "anti-money laundering",
    "antisemitism report",
    "anti-snooping campaign",
    "anti-terrorism",
    "anti-terror legislation",
    "antitrust law",
    "antitrust suit against apple",
    "appeal",
    "appellation of origin",
    "apti",
    "art. 29 wp",
    "article 29 working party",
    "artificial intelligence",
    "assessment",
    "asylum",
    "attacks",
    "audiencia nacional",
    "audiovisual media services directive",
    "authority",
    "authors and performing artists",
    "automated car emergency calls",
    "automated notices",
    "back door",
    "backdoors",
    "back doors",
    "bank account",
    "bank data base",
    "banking data",
    "barack obama",
    "barometer",
    "battlefortheinternet.com",
    "belgian data protection authority",
    "belgium",
    "berec",
    "berne convention",
    "big brother",
    "big brother awards",
    "big brother laws",
    "big data",
    "bilateral cooperation",
    "bill",
    "bill c-51",
    "bill on the protection of citizens security",
    "binding corporate rules",
    "biometric data",
    "biometric database",
    "bitcoin",
    "bitmarkets",
    "bits of freedom",
    "blacklist",
    "black list",
    "blackphone",
    "blanket surveillance",
    "blocking",
    "blocking sites",
    "blocking websites",
    "boip",
    "booklet",
    "border exception",
    "botnet",
    "brief",
    "broadband",
    "broadband connection",
    "broadband reclassification",
    "browsing history",
    "brussels",
    "bufferbloat project",
    "bulgaria",
    "bulk collection",
    "bulk collection of data",
    "bulk data collection",
    "business",
    "business model",
    "cable act",
    "cable privacy",
    "calea",
    "california electronic communications privacy act (calecpa)",
    "calling records",
    "call records",
    "campaign",
    "cars",
    "cartels",
    "case law",
    "cctv",
    "cell-site simulators",
    "censorship",
    "central and eastern europe",
    "ceta",
    "charges for over the top services",
    "charlie hebdo",
    "charter of fundamental rights",
    "child abuse",
    "child pornography",
    "child protection",
    "children",
    "chinese internet filters",
    "chinese regulations",
    "chipset",
    "circumvention",
    "cispa",
    "citizen safety law",
    "citizen security law",
    "citizen's initiative",
    "citizens' security bill",
    "civil liberties",
    "civil rights",
    "civil society",
    "civil society opinion",
    "cjeu",
    "cjeu decision",
    "cjeu ruling on data retention",
    "class action",
    "close down sites",
    "cloud",
    "cloud computing",
    "cloud computing standard",
    "cnil",
    "coalition",
    "code of conduct",
    "code of practice",
    "commission on science and technology for development",
    "committee",
    "committee of ministers",
    "common sense for copyright",
    "communications",
    "communications act",
    "communications assistance for law enforcement act",
    "communications data bill",
    "communications security establishment (cse)",
    "companies",
    "competition",
    "competition law",
    "complaint",
    "computer",
    "computer equipment",
    "computer fraud and abuse act",
    "computer hacking",
    "computer search",
    "computer security",
    "computer threats",
    "consumer protection",
    "conclusions",
    "conference",
    "confidential communications",
    "confidential information",
    "confidentiality",
    "confidentiality of communication",
    "connected devices",
    "connected home devices",
    "consent",
    "consent mechanism",
    "constituent committee",
    "constitution",
    "constitutional court",
    "consultation",
    "consumer data privacy",
    "consumer personal information",
    "consumer privacy",
    "consumer privacy bill",
    "consumer protection",
    "consumer security",
    "content",
    "content aggregation",
    "content removal",
    "contractual clauses",
    "contractual relationships",
    "control",
    "convention",
    "conviction",
    "cookie policy",
    "cookie rules",
    "cookies",
    "cooperation",
    "cooperation procedure",
    "cooperations",
    "co-owner",
    "copyright",
    "copyright and marriage equality act",
    "copyright cases",
    "copyright enforcement",
    "copyright exceptions",
    "copyright industry",
    "copyright infringement",
    "copyright law",
    "copyright limitations",
    "copyright offense",
    "copyright on list of spare parts",
    "copyright performance",
    "copyright protection",
    "copyright reform",
    "copyright regime",
    "corporate secrets",
    "corporate tax",
    "council of europe",
    "counter terrorism",
    "counter-terrorism",
    "counter-terrorism legislation",
    "counter-terror policies",
    "country of origin",
    "court",
    "court case",
    "court cases",
    "court decision",
    "court evidence",
    "court hearing",
    "court intervention",
    "court of justice of the european union",
    "court opinion",
    "court order",
    "court proceedings",
    "court ruling",
    "court trial",
    "court warrant",
    "crime",
    "crime sanctions",
    "crimeware",
    "criminal activity",
    "criminal code",
    "criminal proceedings",
    "critical data",
    "cross-border",
    "crowdsourced copyright reform",
    "cryptografic standards",
    "cryptography",
    "cultural heritage",
    "cultural rights",
    "customer data",
    "customer records",
    "customs control",
    "cyberattacks",
    "cyber attacks",
    "cybercrime",
    "cyberespionage",
    "cyber intelligence sharing and protection act (cispa)",
    "cybersecurity",
    "cyber security",
    "cybersecurity bill",
    "cybersecurity information sharing act (cisa)",
    "cybersecurity law",
    "cybersecurity threat data",
    "cyber threat",
    "czech republic",
    "damages",
    "dancing baby",
    "darknet",
    "dark net",
    "darkweb",
    "dark web",
    "database",
    "database directive",
    "data breach",
    "data breach notification",
    "data broker accountability and transparency act",
    "data brokers",
    "data collection",
    "data flow",
    "data management strategies",
    "data mining",
    "data protection",
    "data protection authorities",
    "data protection authority",
    "data protection directive",
    "data protection eurobarometer",
    "data protection law",
    "data protection reform",
    "data retention",
    "data retention decision",
    "data retention laws",
    "data retention legislation",
    "data roaming",
    "data security",
    "data sharing",
    "data storage",
    "data theft",
    "data transfer",
    "data transfers",
    "david cameron",
    "ddos",
    "debate",
    "decision",
    "declaration",
    "defamation",
    "defence",
    "defense",
    "defense department regulation",
    "definition",
    "de-index urls",
    "delete music",
    "delfi case",
    "delisting",
    "de-listing",
    "delisting of personal data",
    "de-listing urls",
    "delisting urls",
    "denial of service",
    "denmark",
    "developing countries",
    "developments",
    "device",
    "dg connect",
    "dg markt",
    "dhl",
    "diacritical characters",
    "diacritics",
    "dialogue",
    "digital",
    "digital age",
    "digital agenda",
    "digital assistant",
    "digital bill",
    "digital by default",
    "digital challenges",
    "digital citizenship",
    "digital currency",
    "digital divide",
    "digital economy",
    "digital government",
    "digital growth",
    "digital identity",
    "digitalisation",
    "digitalization",
    "digital media",
    "digital millennium copyright act",
    "digital millennium copyright act (dmca)",
    "digital policies",
    "digital policy",
    "digital rights",
    "digital rights ireland",
    "digital rights management",
    "digital security",
    "digital services",
    "digital single market",
    "digital strategy",
    "digital vigilantism",
    "digital wallet",
    "digital weapons",
    "dimitris avramopoulos",
    "directive",
    "directive 2006/24/ec",
    "directive 2011/77/eu",
    "directive 2012/28/eu",
    "disabled persons",
    "discussions",
    "distinctive character",
    "distribution right",
    "dmca",
    "dna",
    "document",
    "documentary",
    "document leak",
    "document pool",
    "document release",
    "documents",
    "doj",
    "domain name",
    "domain names",
    "domain name system",
    "domain name system (dns)",
    "domain registrants",
    "domain registration",
    "domains",
    "domain seizure",
    "domain names",
    "dos attack",
    "double irish",
    "doxbin",
    "dpa",
    "draft",
    "draft bill",
    "draft communication",
    "draft guidelines",
    "draft law",
    "draft proposal",
    "drip",
    "drm",
    "droit de suite",
    "drone",
    "drone regulation",
    "drones",
    "drone strike",
    "drug trafficking",
    "dutch data protection authority",
    "eavesdropping",
    //"ec",
    "ecall",
    "echr",
    "ecj",
    "ecj decision",
    "ecj ruling",
    "ec model clauses",
    "e-commerce",
    "economic boom",
    "economic sanctions",
    "edps",
    "edps ethics board",
    "edri",
    "edward snowden",
    "education",
    "e-estonian",
    "eff",
    "egovernment",
    "e-government",
    "eid",
    "eidas regulation",
    "e-identification",
    "electronic communications",
    "electronic communications privacy act",
    "electronic communications privacy act (ecpa)",
    "electronic frontier foundation",
    "electronic identification",
    "electronic signatures",
    "email privacy act",
    "email privacy bills",
    "emails",
    "emergency call system",
    "employee's data",
    "employer's database",
    "encryption",
    "encryption keys",
    "encryption techniques",
    "enforcement",
    "engagement",
    "enhanced powers",
    "enterprise products",
    "entrepreneurship",
    "epic",
    "epo",
    "eprivacy",
    "eprivacy directive",
    "equal",
    "e-residency",
    "estonia",
    "ethics",
    //"eu",
    "eu-canada",
    "eu charter of fundamental rights",
    "eu council",
    "eu data protection law",
    "eu data protection reform",
    "eu documents",
    "eu framework",
    "eu internet forum",
    "eu law",
    "eu legislation",
    "eu pnr directive",
    "eu pnr proposal",
    "europe",
    "european bodies",
    "european charter of fundamental rights",
    "european cloud",
    "european commission",
    "european commissioner for digital economy",
    "european convention on human rights",
    "european convention on human rights (echr)",
    "european copyright society",
    "european court of human rights (echr)",
    "european court of justice",
    "european data protection supervisor (edps)",
    "european design law",
    "european directive",
    "european law",
    "european ombudsman",
    "european parliament",
    "european patent office",
    "european patent organization",
    "european union",
    "european values",
    "europe v facebook",
    "europol",
    "eusfta",
    "eu telecommunications framework",
    "eu-us",
    "ewg",
    "exclusive right vs monopoly right",
    "executive order",
    "exhaustion principle",
    "explanatory note",
    "extraterritorial execution of warrants",
    "facebook post search",
    "facial recognition",
    "fair use",
    "family businesses",
    "fast track",
    "fast track adoption",
    "fbi",
    "fcc",
    "fcc vote",
    "federal aviation administration",
    "federal communications commission",
    "federal communications commission (fcc)",
    "federal court",
    "federal crime",
    "federal trade commission",
    "federal trade commission (ftc)",
    "file sharing",
    "filtering",
    "final version",
    "final vote",
    "financial data",
    "fingerprints",
    "finland",
    "fisc",
    "flight data",
    "foia request",
    "folklore",
    "football club",
    "ford",
    "foreign intelligence surveillance court",
    "foreign policy",
    "formal notice",
    "fourth amendment",
    "framework",
    "framework for electronic communications networks and services",
    "france",
    "free",
    "freedom act",
    "freedom not fear",
    "freedom of expression",
    "freedom of panorama",
    "freedom of speech",
    "freedom of the press",
    "free speech",
    "free trade",
    "french surveillance bill",
    "friend of the court brief",
    "friend-of-the-court brief",
    "ftc",
    "fundamental rights",
    "funding",
    "garcia vs google",
    "gdpr",
    "general approach",
    "general data protection regulation",
    "generic top-level domains",
    "geneva digital watch",
    "geneva internet platform",
    "geo-blocking",
    "geographical indications",
    "german government",
    "germany",
    "giovanni buttarelli",
    "giplatform",
    "gipo",
    "global community",
    "global domains",
    "global policy",
    "global trend",
    "google",
    "google advisory council",
    "google fiber",
    "google news spain",
    "google search for kids",
    "google tax",
    "google vs spain",
    "governmental programme",
    "government data requests",
    "government initiative",
    "government plan",
    "government policy",
    "government requests",
    "government transparency",
    "gpen",
    "gtld program",
    "guenther oettinger",
    "guidance",
    "guidelines",
    "guidelines on online literature",
    "gunther oettinger",
    "hackers",
    "hacking",
    "hacking attacks",
    "hadopi",
    "harassment",
    "harmonization",
    "hate crimes",
    "hate speech",
    "health data",
    "hearing",
    "hearings",
    "hidden camera",
    "high court of cassation and justice",
    "high-speed",
    "high-tech",
    "hollande",
    "home affairs commissioner",
    "home copy",
    "home copying levies",
    "home use",
    "house of lords",
    "https protocol",
    "https",
    "human rights",
    "human rights council",
    "human rights record in geneva",
    "human rights violation",
    "hyperlinks",
    "iana contract",
    "iana functions",
    "iana stewardship transition coordination group",
    "iana transition",
    "icann",
    "icann meeting",
    "ict",
    "id cards",
    "idn",
    "ietf",
    "if this then that",
    "igf",
    "iipa",
    "illegal consumption",
    "illegal content",
    "illegal copying",
    "illegal downloading",
    "illegal downloads",
    "illegal interceptions",
    "illegal operations",
    "illegal phone tapping",
    "illegal search",
    "implementation",
    "implications",
    "imsi catchers",
    "in-camera session",
    "industry",
    "industry associations",
    "information service",
    "information services",
    "information sharing",
    "information sharing system",
    "information society",
    "information technology industry council",
    "infosoc directive",
    "infrastructure",
    "infringement",
    "infringements",
    "injunction",
    "injunctions",
    "innovation",
    "innovation act",
    "inspection",
    "intellectual commons",
    "intellectual property",
    "intellectual property hub",
    "intellectual property law",
    "intellectual property rights",
    "intelligence",
    "intelligence activities",
    "intelligence agencies",
    "intelligence agency",
    "intelligence authorization act",
    "intelligence bill",
    "intelligence center",
    "intelligence codex",
    "intelligence operations",
    "intelligence services",
    "intercept",
    "interception",
    "interception of communications",
    "interceptions",
    "intergroup",
    "intermediaries",
    "internal market",
    "international affairs",
    "international conference",
    "international law",
    "international meeting",
    "international organization for standardization (iso)",
    "international privacy specialists",
    "international standard",
    "international surveillance powers",
    "international telecommunications union",
    "international telecommunication union (itu)",
    "international trade agreements",
    "internet",
    "internet access",
    "internet as a human right",
    "internet bill of rights",
    "internet blocking",
    "internet body",
    "internet companies",
    "internet constitution",
    "internet core functions",
    "internet engineering steering group (iesg)",
    "internet exchange points (ixps)",
    "internet freedom",
    "internet governance",
    "internet governance forum",
    "internet governance hub",
    "internet layer",
    "internet monitoring",
    "internet of things",
    "internet of things (iot)",
    "internet policy",
    "internet policy observatory",
    "internet protocol",
    "internet providers",
    "internet regulation",
    "internet service providers",
    "internet speed",
    "internet traffic",
    "internet traffic monitoring",
    "internet ungovernance forum",
    "invalid",
    "inventions",
    "inventive step",
    "investigation",
    "investigations",
    "investigatory powers bill",
    "investigatory powers tribunal",
    "investigatory powers tribunal (ipt)",
    "investment",
    "investors",
    "investor state dispute settlement (isds)",
    "investor-state dispute settlement (isds)",
    "investor-to-state dispute settlement",
    "iot",
    "ip address",
    "ip addresses",
    "ipen",
    "ip offices",
    "ip protection",
    "ipr",
    "ipr infringement",
    "ipr protection",
    "ireland",
    "irish datacenters",
    "irish data protection",
    "irishgenealogy.ie",
    "isco",
    "isds",
    "isis",
    "iso 27018",
    "iso 27001",
    "isp",
    //"it",
    "italian data protection authority",
    "italian presidency",
    "italy",
    "it companies",
    "it security",
    "itu",
    "itu plenipotentiary conference",
    "jailbreak",
    "jewel v. nsa",
    "jihad",
    "joint research center",
    "joint statement",
    "journalism",
    "journalist",
    "journalists",
    "judgment",
    "judicial",
    "judicial oversight",
    "julia reda",
    "julien assange",
    "jurisdiction",
    "jurisprudence",
    "keynote speech",
    "kill switches",
    "klayman v. obama",
    "knowledge development box tax scheme",
    "law",
    "law enforcement",
    "law overview copyright",
    "law proposal",
    "law reform",
    "lawsuit",
    "law suit",
    "law suits",
    "leak document",
    "leak documents",
    "leaked document",
    "leaked documents",
    "leaks",
    "least developed countries",
    "legal action",
    "legal basis",
    "legal campaign",
    "legal committee",
    "legal context",
    "legal framework",
    "legal notice",
    "legal process",
    "legal service report",
    "legal study",
    "legislation",
    "legislative proposal",
    "legislative proposals",
    "legitimate purpose",
    "letter",
    "liability",
    "libe committee",
    "libe vote",
    "links",
    "live streaming",
    "lobby",
    "local",
    "location",
    "login credentials",
    "loopholes",
    "low privacy protection",
    "mac addresses",
    "magna carta",
    "magna carta of the internet",
    "magna charta",
    "malta",
    "manila principles on internet liability",
    "marco civil",
    "marietje schaake",
    "mark schrems",
    "mass spying",
    "mass surveillance",
    "max schrems",
    "media",
    "media industry",
    "medical data",
    "medical records",
    "meeting",
    "memorandum",
    "memorandum of understanding",
    "mere conduit",
    "merkel",
    "metadata",
    "microchip implants in humans",
    "ministry of public finance",
    "misuse of data",
    "mobile",
    "mobile apps",
    "mobile devices",
    "mobile operators",
    "mobile phones",
    "mobile providers",
    "mobile users",
    "moldova",
    "monaco v ohim",
    "money laundering",
    "monitoring",
    "monitoring tools",
    "monkey selfie case",
    "monopoly",
    "motion picture association of america (mpaa)",
    "mou",
    "multistakeholder",
    "multistakeholder model",
    "names and numbers",
    "nasdaq",
    "national crime agency",
    "national database",
    "national database with tourists",
    "national igf",
    "national law",
    "national security",
    "national security agency",
    "national security letter",
    "nca",
    "necessary and proportionate",
    "neelie kroes",
    "negotiations",
    "netherlands",
    "netmundial",
    "netmundial initiative",
    "net neutrality",
    "net-neutrality",
    "net neutrality debate",
    "net neutrality framework",
    "network",
    "network and information security",
    "new agreement",
    "new amendments",
    "new bill",
    "new documents",
    "new framework",
    "new gtlds",
    "new law",
    "new law proposal",
    "new legal proposal",
    "new legislation",
    "newly proposed bill",
    "new regulation",
    "new rules",
    "new software",
    "new technologies",
    "next generation identification program",
    "ngo",
    "nis directive",
    "nist",
    "no disconnect strategy",
    "non-citizens",
    "notice",
    "notification",
    "nsa",
    "nsa program reauthorization",
    "ntia",
    "obama",
    "oecd report",
    "offensive content",
    "ogp",
    "ohim",
    "online",
    "online accounts",
    "online activity",
    "online banking",
    "online behaviour",
    "online billing",
    "online censorship",
    "online drug marketplace",
    "online freedom",
    "online gambling",
    "online harassment",
    "online information",
    "online infringement",
    "online linking to content",
    "online media",
    "online monitoring",
    "online newspaper",
    "online petition",
    "online piracy",
    "online platform",
    "online platforms",
    "online portal",
    "online profiling",
    "online restrictions",
    "online security",
    "online speech",
    "online surveillance",
    "online tool",
    "online voting",
    "open",
    "open access",
    "open data",
    "open data incubator",
    "open internet",
    "open invention network",
    "open letter",
    "open platforms",
    "open software",
    "open source",
    "open source software",
    "opinion",
    "opt out",
    "opt-out",
    "oracle vs google",
    "oral arguments",
    "order",
    "original works",
    "orphan works",
    "orphan works database",
    "outcome",
    "outcomes",
    "oversight",
    "overview",
    "panel",
    "panopticlick",
    "panoptykon foundation",
    "paris attacks",
    "parliament",
    "passenger name record (pnr)",
    "passenger name records",
    "passenger name records (pnr)",
    "passwords",
    "patch management process",
    "patent",
    "patent applications",
    "patent claims",
    "patent law",
    "patent reform",
    "patent register",
    "patent trolls",
    "patriot act",
    "peer-to-peer",
    "penal code",
    "penalty",
    "performance",
    "permissions",
    "permitted uses",
    "personal audio",
    "personal data",
    "personal data law",
    "personal data protection",
    "personal data transfer",
    "personal information",
    "personality rights",
    "personal stamp",
    "personal use",
    "petition",
    "pharmaceutical products",
    "phone records",
    "piracy",
    "piracy app",
    "pirate bay",
    "pirate party",
    "pirate websites",
    "place recognition",
    "platform",
    "platform neutrality",
    "plenipot",
    "pnr",
    "pnr system",
    "poland",
    "police",
    "police body cameras",
    "policies",
    "policy",
    "policy decision",
    "policy-making process",
    "polish gambling act",
    "political party",
    "portugal",
    "positive discrimination",
    "preliminary ruling",
    "prepaid sim card registration",
    "prepay sim cards",
    "principle of territoriality",
    "principles",
    "prioritization",
    "prism",
    "privacy tools",
    "privacy",
    "privacy and civil liberties oversight board (pclob)",
    "privacy app store",
    "privacy assessment",
    "privacy at workspace",
    "privacy audits",
    "privacy bill",
    "privacy camp",
    "privacy campaign",
    "privacy concerns",
    "privacy controls",
    "privacy enhancing techniques (pet)",
    "privacy impact assessment",
    "privacy law",
    "privacy laws",
    "privacy law violation",
    "privacy policy",
    "privacy protection",
    "privacy risks",
    "privacy rules",
    "privacy settings",
    "privacy shield",
    "privacy sweep",
    "privacy tool",
    "privacy tools",
    "privacy violation",
    "privacy violations",
    "privacy watchdog",
    "private companies",
    "private copies",
    "private copy",
    "private phone records",
    "private selling app",
    "private use",
    "privatised censorship",
    "privileged communications",
    "procedure",
    "process",
    "procurement",
    "profile",
    "profiling",
    "project",
    "proportionate",
    "proposal",
    "prosecution",
    "protected content",
    "protection",
    "protection mechanisms",
    "protests",
    "protocol",
    "protocols",
    "proxy services",
    "pseudonym",
    "public authorities",
    "public buildings",
    "public comment",
    "public comments",
    "public consultation",
    "public debate",
    "public hearing",
    "public information",
    "public interest",
    "public opinion",
    "public oversight",
    "public policy",
    "public records",
    "public safety",
    "public transport",
    "public utility",
    "rapporteur ecall",
    "ratification",
    "raynor v. state of maryland",
    "real name policy",
    "reauthorization",
    "reciprocity of recognition",
    "reclassification",
    "reclassification of broadband services",
    "recommendation",
    "recommendations",
    "reform",
    "reform law",
    "reform package",
    "regional summit",
    "register",
    "registrar",
    "registry",
    "regulation",
    "regulation of investigatory powers act 2000 (ripa)",
    "regulation of investigatory powers act (ripa)",
    "regulator",
    "regulatory power",
    "released files",
    "remote access",
    "remote search",
    "remove content requests",
    "renewal",
    "report",
    "reporting",
    "resale right",
    "research",
    "research paper",
    "resolution",
    "restrictions",
    "results",
    "retention",
    "review",
    "revision",
    "rf id devices",
    "rights",
    "rights and obligations",
    "right to be forgotten",
    "right to information",
    "rir",
    "roadmap",
    "roaming",
    "roaming charges",
    "romania",
    "romanian constitutional court",
    "romanian constitutional court (ccr)",
    "romanian ministry of defense",
    "romania supreme court",
    "rule of law",
    "ruling",
    "safe cloud",
    "safeguards",
    "safe harbor",
    "safe harbor decision",
    "safe harbour",
    "safety",
    "sanctions",
    "savetheinternet.eu",
    "scan",
    "scheme",
    "schrems",
    "schrems case",
    "scientific research",
    "search and seizure",
    "search engine",
    "search engines",
    "search results",
    "search warrant",
    "secret court",
    "secret mobile tracking program",
    "secret service",
    "secret services",
    "secret text",
    "section 215",
    "secure data act",
    "security",
    "security agencies",
    "security bill",
    "security policy",
    "security requirements for apps",
    "security services",
    "seized site",
    "seize emails",
    "seizure",
    "self-regulation",
    "seminar",
    "senators on the commerce committee",
    "sensitive data",
    "sensitive information",
    "sentence",
    "sensors",
    "server",
    "server farm",
    "services for skipping ads",
    "sharing devices",
    "shutdown",
    "shut down account",
    "silk road",
    "silk road 2.0 site",
    "silverpush",
    "sim cards",
    "sim cards hack",
    "sir tim berners-lee",
    "site blocking",
    "slovak constitutional court",
    "smart id cards",
    "smartphone driver's license",
    "smartphone password",
    "smartphones",
    "smart tv",
    "smith v. obama",
    "snooper's charter",
    "snoopers charter",
    "snooping",
    "snowden",
    "snowden revelations",
    "snowden treaty",
    "social media",
    "social media monitor",
    "social network",
    "social networks",
    "software",
    "software companies",
    "spain",
    "spanish court",
    "spanish criminal code",
    "spanish google tax law",
    "spanish lpi",
    "spare parts",
    "specialist unit",
    "special rapporteur",
    "speed",
    "private life",
    "spy agency",
    "spying",
    "spying programs",
    "standard",
    "standard contractual clauses",
    "standards",
    "startup",
    "startups",
    "start-ups",
    "statement",
    "state office for inventions and trademarks",
    "state secrets",
    "state secrets law",
    "state security",
    "state v. davis",
    "statistics",
    "strategy",
    "streaming hardware",
    "street view",
    "strong patents act",
    "student data",
    "study",
    "sub-arctic",
    "subsidize",
    "suicidal content",
    "suicidal thoughts",
    "sui generis right",
    "summit",
    "super cookie",
    "super-cookie",
    "supercookies",
    "superfish software",
    "support",
    "survaillance agencies",
    "surveillance",
    "surveillance bill",
    "surveillance laws",
    "surveillance program",
    "surveillance reform",
    "surveillance technologies",
    "surveillance tools",
    "survey",
    "sweden",
    ".swiss",
    "switzerland",
    "table",
    "takedown",
    "take down",
    "takedown notice",
    "takedown notices",
    "tapping",
    "targeted ads",
    "task force",
    "tax",
    "tax collection",
    "taxes",
    "tax loophole",
    "tech companies",
    "technology",
    "technology policy",
    "technology trends",
    "telecom",
    "telecommunications",
    "telecommunications service",
    "telecom operators",
    "telecom providers",
    "telecom single market",
    "telecoms regulation",
    "telecoms single market",
    "telecoms single market regulation",
    "tender",
    "tenders",
    "terrorism",
    "terrorism crimes",
    "terrorist",
    "testing",
    "theft",
    "the great firewall of china",
    "the netherlands",
    "the pirate bay",
    "think tank",
    "third countries",
    "third parties",
    "third world countries",
    "tisa",
    "tisa trade agreement",
    "tool",
    "tools",
    "top level domain name",
    "tor",
    "torrents",
    "torrent sites",
    "torrent websites",
    "tpp",
    "track drivers",
    "tracking",
    "tracking communications",
    "tracking program",
    "tracking sensitive data",
    "tracking technology",
    "trade",
    "trade agreement",
    "trade agreements",
    "trade in services agreement (tisa)",
    "trademark",
    "trade mark",
    "trademarks",
    "trade negotiations",
    "trade secrets",
    "trade secrets directive",
    "traditional knowledge",
    "traffic data",
    "traffic interception",
    "transatlantic",
    "transatlantic trade and investment partnership",
    "trans-atlantic trade and investment partnership (ttip)",
    "transatlantic trade and investment partnership (ttip)",
    "transfer of personal data",
    "transfers of personal data",
    "trans-pacific partnership",
    "trans-pacific partnership agreement (tpp)",
    "trans-pacific partnership (tpp)",
    "transparency",
    "transparency report",
    "transparency reports",
    "transposed directive",
    "tranzition",
    "transition",
    "treaty",
    "tree strikes and you are out",
    "trends",
    "trialogue",
    "trips",
    "trust",
    "trust services",
    "ttip",
    "ttip negociations",
    "ttip negotiations",
    "ttp",
    "twitter",
    //"uk",
    "uk communications bill",
    "uk communications data bill",
    "uk information commissioner's office",
    "uk parliament",
    "uk seller",
    "umbrella agreement",
    //"un",
    "unauthorized access",
    "unauthorized copying of data",
    "unconstitutional",
    "undeletable cookie",
    "undeletable cookies",
    "undesa",
    "un general assembly",
    "unhrc",
    "un human rights committee",
    "un human rights council",
    "un human rights council review",
    "unified patent court agreement",
    "unites states vs vargas",
    "universal periodic review (upr)",
    "unlawful",
    "unmanned aerial vehicles",
    "unmanned aircraft",
    "un report on copyright",
    "un resolution",
    "un special rapporteur",
    "update",
    "url",
    "url delisting",
    //"us",
    "usa freedom act",
    "us congress",
    "us court",
    "us department of justice",
    "us district court",
    "use it or leave it",
    "user consent",
    "user data",
    "user protection",
    "user rights",
    "us espionage",
    "us federal court",
    "us freedom act",
    "us patent and trademark office",
    "us privacy act to eu citizens",
    "us servers",
    "video recording",
    "video section",
    "violation",
    "voice recognition",
    "vote",
    "vpn",
    "waiver extension",
    "warning",
    "warrant",
    "watchdog",
    "web and phone data",
    "web company",
    "web foundation",
    "webinar",
    "web index",
    "web service",
    "website blocking",
    "websites",
    "web summit",
    "web traffic",
    "week of action",
    "weltimmo case",
    "whistleblowers",
    "whistleblowing",
    "whois",
    "whois database",
    "wifi",
    "wi-fi",
    "wi-fi routers",
    "wi-fi tracking technology",
    "wifi user registration",
    "wikimedia",
    "wipo",
    "wireless technology",
    "wojciech",
    "working document",
    "working group",
    "workshop",
    "world conference on international telecommunications (wcit)",
    "world economic forum",
    "world summit on the information society (wsis)",
    "wsis",
    "wsis+10",
    "youth",
    "youth organizations",
    "youtube for kids",
    "zero rating",
    "traffic management",
    "specialized services",
    "specialised services",
    "zombie cookies",
    "civil liberties",
    "privacy infringement",
    "data protection infringement",
    "data protection violation",
    "Internet privacy",
    "computer emergency response team",
    "computer network security",
    "computer security",
    "crime prevention",
    "cyberwarfare",
    "body of european regulators in electronic communications",
    "enisa",
    "european union agency for network information security",
    "governance",
    "icann",
    "internet service provider",
    "national security",
    "austria",
    "online behavior",
  ];
}

})();
